FROM opensuse/tumbleweed:latest

RUN zypper dup -y && zypper in -y --no-recommends \
  git git-lfs ca-certificates curl jq unzip xz zstd nodejs nodejs-npm python3 go

RUN VERSION=$(curl -s "https://help.perforce.com/helix-core/release-notes/current/relnotes.txt" | grep -oP -m1 "(?<=Version 20)\d\d\.\d") \
  && curl -sL "https://filehost.perforce.com/perforce/r$VERSION/bin.linux26x86_64/p4" -o /usr/local/bin/p4 \
  && chmod 755 /usr/local/bin/p4

RUN zypper clean && rm -rf /tmp/* /var/cache/zypp /var/log/*