FROM ubuntu:noble

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get -y upgrade
RUN apt-get update && apt-get -y install --no-install-recommends \
  git git-lfs ca-certificates curl jq unzip xz-utils zstd
ENV PATH "/opt/node/bin:$PATH"
RUN VERSION=$(curl -s "https://nodejs.org/dist/index.json" | jq -r "map(select(.lts))[0].version") \
  && curl -s "https://nodejs.org/dist/$VERSION/node-$VERSION-linux-x64.tar.xz" | tar -xJ --one-top-level=/opt/node --strip-components=1 \
  && find /opt/node/include/node/openssl/archs -mindepth 1 -maxdepth 1 -not -name "linux-x86_64" -exec rm -rf {} +

RUN VERSION=$(curl -s "https://help.perforce.com/helix-core/release-notes/current/relnotes.txt" | grep -oP -m1 "(?<=Version \d\d)\d\d\.\d") \
  && curl -s "https://filehost.perforce.com/perforce/r$VERSION/bin.linux26x86_64/p4" -o /usr/local/bin/p4 \
  && chmod 755 /usr/local/bin/p4

RUN apt clean && rm -rf /tmp/* /var/cache/* /var/lib/apt/lists/* /var/log/*
