FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get -y upgrade
RUN apt-get update && apt-get -y install --no-install-recommends \
  git git-lfs ca-certificates curl jq unzip xz-utils zstd

RUN VERSION=$(curl -s "https://help.perforce.com/helix-core/release-notes/current/relnotes.txt" | grep -oP -m1 "(?<=Version 20)\d\d\.\d") \
  && curl -sL "https://filehost.perforce.com/perforce/r$VERSION/bin.linux26x86_64/p4" -o /usr/local/bin/p4 \
  && chmod 755 /usr/local/bin/p4

ENV PATH="/opt/node/bin:$PATH"
RUN VERSION=$(curl -s "https://nodejs.org/dist/index.json" | jq -r "map(select(.lts))[0].version") \
  && curl -sL "https://nodejs.org/dist/$VERSION/node-$VERSION-linux-x64.tar.xz" | tar -xJ --one-top-level=/opt/node --strip-components=1 \
  && find /opt/node/include/node/openssl/archs -mindepth 1 -maxdepth 1 -not -name "linux-x86_64" -exec rm -rf {} +

ENV PATH="/opt/python/bin:$PATH"
RUN VERSION=$(curl -s "https://docs.python.org/3/index.html" | grep -oP -m1 "(?<=Python )3\.\d+\.\d+") \
  && RELEASE_TAG=$(curl -s "https://api.github.com/repos/astral-sh/python-build-standalone/releases/latest" | jq -r ".tag_name") \
  && curl -sL "https://github.com/astral-sh/python-build-standalone/releases/download/$RELEASE_TAG/cpython-$VERSION+$RELEASE_TAG-x86_64-unknown-linux-gnu-install_only_stripped.tar.gz" | tar -xz --one-top-level=/opt/python --strip-components=1

ENV PATH="/opt/go/bin:$PATH"
RUN VERSION=$(curl -s "https://go.dev/dl/?mode=json" | jq -r ".[0].version") \
  && curl -sL "https://go.dev/dl/$VERSION.linux-amd64.tar.gz" | tar -xz --one-top-level=/opt/go --strip-components=1

RUN apt clean && rm -rf /tmp/* /var/cache/* /var/lib/apt/lists/* /var/log/*
