FROM fedora:rawhide

RUN dnf -y upgrade && dnf -y --setopt=install_weak_deps=false install \
  git git-lfs patch cmake clang python python-pip nodejs nodejs-npm golang rust

RUN VERSION=$(curl -s "https://help.perforce.com/helix-core/release-notes/current/relnotes.txt" | grep -oP -m1 "(?<=Version 20)\d\d\.\d") \
  && curl -sL "https://filehost.perforce.com/perforce/r$VERSION/bin.linux26x86_64/p4" -o /usr/local/bin/p4 \
  && chmod 755 /usr/local/bin/p4

RUN dnf clean all && rm -rf /tmp/* /var/cache/dnf /var/log/*
