name: Build

on:
  push:
    branches: [main]
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.image }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        image: [alpine, fedora]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Login to ghcr.io
        run: buildah login ghcr.io -u "${{ github.actor }}" -p "${{ github.token }}"

      - name: Build and push image
        run: |
          buildah build --squash --omit-history --tag ghcr.io/mashizora/${{ matrix.image }}:latest ${{ matrix.image }}
          buildah push ghcr.io/mashizora/${{ matrix.image }}:latest

      - name: Clean old versions
        env:
          GH_TOKEN: ${{ github.token }}
        run: >
          gh api /user/packages/container/${{ matrix.image }}/versions
          | jq '.[]|select(.metadata.container.tags|contains(["latest"])|not)|.id'
          | xargs -I{} gh api -X DELETE /user/packages/container/${{ matrix.image }}/versions/{}
